swagger: '2.0'
info:
  description: Something about the API
  version: '1.0.0'
  title: 'Test API'
basePath: '/api/v1'
schemes:
  - 'https'
  - 'http'
paths:
  /:
    get:
      tags:
        - 'root'
      summary: 'Get API Version Information'
      description: 'Returns a list of the available API versions'
      operationId: 'versions'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'success'
          schema:
            $ref: '#/definitions/ArrayOfVersions'
  /ping:
    get:
      tags:
        - 'root'
      summary: 'Get Server Information'
      description: 'Returns information about the server'
      operationId: 'ping'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'success'
          schema:
            $ref: '#/definitions/ServerInfo'
definitions:
  # see https://swagger.io/docs/specification/data-models/data-types
  APIVersion:
    type: 'object'
    properties:
      version:
        type: 'integer'
        format: 'int64'
      path:
        type: 'string'
  ServerInfo:
    type: 'object'
    properties:
      name:
        type: 'string'
      description:
        type: 'string'
      version:
        type: 'string'
      uptime:
        type: 'number'
  ArrayOfVersions:
    type: 'array'
    items:
      $ref: '#/definitions/APIVersion'
